[package]
name = "mercy"
version = "1.1.11"
edition = "2021"
authors = ["Hifumi1337"]
license = "BSD-2-Clause"
categories = ["cryptography", "encoding"]
keywords = ["hashing", "decode", "encode", "cracking"]
description = "Mercy is a public Rust crate created to assist with building cybersecurity frameworks, assessment tools, and numerous other projects"
repository = "https://github.com/hifumitech/mercy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
sha2 = "0.10"
md5 = "0.7.0"
hexdump = "0.1.1"
sys-info = "0.9.0"